# Generated by Django 5.2.8 on 2025-11-13 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'événement")),
                ('date', models.DateTimeField(verbose_name='Date et heure')),
                ('description', models.TextField(verbose_name='Description')),
                ('capacite', models.IntegerField(verbose_name='Capacité')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImageEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evenements/%Y/%m/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Image principale')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evenement.evenement', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Image d'événement",
                'verbose_name_plural': "Images d'événements",
                'ordering': ['-est_principale', '-uploaded_at'],
            },
        ),
    ]
